<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Ksb;
use App\Models\Course;

class KsbSeeder extends Seeder
{
    public function run()
    {
        
        $dev = Course::where('name', 'Software Developer Level 4')->first();
        $testing = Course::where('name', 'Software Tester Level 4')->first();
        $apm_l4 = Course::where('name', 'Associate Project Manager Level 4')->first();
        $acc = Course::where('name', 'Digital Accessibility Specialist Level 4')->first();
        $cyber_security_l4 = Course::where('name', 'Cyber Security Level 4')->first();
        $dev_ops = Course::where('name', 'Dev Ops Level 4')->first();
        $dpm_l4 = Course::where('name', 'Digital Product Management Level 4')->first();
        $data_eng_l5 = Course::where('name', 'Data Engineering Level 5')->first();
        $data_an_l4 = Course::where('name', 'Data Analyst Level 4')->first();
        $cloud_l3 = Course::where('name', 'Cloud Specialist Level 3')->first();


        $ksbs = [
            // Knowledge KSBs for Software Developer Level 4
            ['course_id' => $dev->id, 'type' => 'knowledge', 'identifier' => 'K1', 'description' => 'All stages of the software development life-cycle (what each stage contains, including the inputs and outputs).'],
            ['course_id' => $dev->id, 'type' => 'knowledge', 'identifier' => 'K2', 'description' => 'Roles and responsibilities within the software development lifecycle (who is responsible for what).'],
            ['course_id' => $dev->id, 'type' => 'knowledge', 'identifier' => 'K3', 'description' => 'The roles and responsibilities of the project life-cycle within your organisation, and your role.'],
            ['course_id' => $dev->id, 'type' => 'knowledge', 'identifier' => 'K4', 'description' => 'How best to communicate using the different communication methods and how to adapt appropriately to different audiences.'],
            ['course_id' => $dev->id, 'type' => 'knowledge', 'identifier' => 'K5', 'description' => 'The similarities and differences between different software development methodologies, such as agile and waterfall.'],
            ['course_id' => $dev->id, 'type' => 'knowledge', 'identifier' => 'K6', 'description' => 'How teams work effectively to produce software and how to contribute appropriately.'],
            ['course_id' => $dev->id, 'type' => 'knowledge', 'identifier' => 'K7', 'description' => 'Software design approaches and patterns, to identify reusable solutions to commonly occurring problems.'],
            ['course_id' => $dev->id, 'type' => 'knowledge', 'identifier' => 'K8', 'description' => 'Organisational policies and procedures relating to the tasks being undertaken, and when to follow them. For example the storage and treatment of GDPR sensitive data.'],
            ['course_id' => $dev->id, 'type' => 'knowledge', 'identifier' => 'K9', 'description' => 'Algorithms, logic and data structures relevant to software development.'],
            ['course_id' => $dev->id, 'type' => 'knowledge', 'identifier' => 'K10', 'description' => 'Principles and uses of relational and non-relational databases.'],
            ['course_id' => $dev->id, 'type' => 'knowledge', 'identifier' => 'K11', 'description' => 'Software designs and functional or technical specifications.'],
            ['course_id' => $dev->id, 'type' => 'knowledge', 'identifier' => 'K12', 'description' => 'Software testing frameworks and methodologies.'],

            // Skills KSBs for Software Developer Level 4
            ['course_id' => $dev->id, 'type' => 'skills', 'identifier' => 'S1', 'description' => 'Create logical and maintainable code.'],
            ['course_id' => $dev->id, 'type' => 'skills', 'identifier' => 'S2', 'description' => 'Develop effective user interfaces.'],
            ['course_id' => $dev->id, 'type' => 'skills', 'identifier' => 'S3', 'description' => 'Link code to data sets.'],
            ['course_id' => $dev->id, 'type' => 'skills', 'identifier' => 'S4', 'description' => 'Test code and analyse results to correct errors found using unit testing.'],
            ['course_id' => $dev->id, 'type' => 'skills', 'identifier' => 'S5', 'description' => 'Conduct a range of test types, such as Integration, System, User Acceptance, Non-Functional, Performance and Security testing.'],
            ['course_id' => $dev->id, 'type' => 'skills', 'identifier' => 'S6', 'description' => 'Identify and create test scenarios.'],
            ['course_id' => $dev->id, 'type' => 'skills', 'identifier' => 'S7', 'description' => 'Apply structured techniques to problem solving, debug code and understand the structure of programs in order to identify and resolve issues.'],
            ['course_id' => $dev->id, 'type' => 'skills', 'identifier' => 'S8', 'description' => 'Create simple software designs to effectively communicate understanding of the program.'],
            ['course_id' => $dev->id, 'type' => 'skills', 'identifier' => 'S9', 'description' => 'Create analysis artefacts, such as use cases and/or user stories.'],
            ['course_id' => $dev->id, 'type' => 'skills', 'identifier' => 'S10', 'description' => 'Build, manage and deploy code into the relevant environment.'],
            ['course_id' => $dev->id, 'type' => 'skills', 'identifier' => 'S11', 'description' => 'Apply an appropriate software development approach according to the relevant paradigm (for example object oriented, event driven or procedural).'],
            ['course_id' => $dev->id, 'type' => 'skills', 'identifier' => 'S12', 'description' => 'Follow software designs and functional or technical specifications.'],
            ['course_id' => $dev->id, 'type' => 'skills', 'identifier' => 'S13', 'description' => 'Follow testing frameworks and methodologies.'],
            ['course_id' => $dev->id, 'type' => 'skills', 'identifier' => 'S14', 'description' => 'Follow company, team or client approaches to continuous integration, version and source control.'],
            ['course_id' => $dev->id, 'type' => 'skills', 'identifier' => 'S15', 'description' => 'Communicate software solutions and ideas to technical and non-technical stakeholders.'],
            ['course_id' => $dev->id, 'type' => 'skills', 'identifier' => 'S16', 'description' => 'Apply algorithms, logic and data structures.'],
            ['course_id' => $dev->id, 'type' => 'skills', 'identifier' => 'S17', 'description' => 'Interpret and implement a given design whilst remaining compliant with security and maintainability requirements.'],

            // Behaviours KSBs for Software Developer Level 4
            ['course_id' => $dev->id, 'type' => 'behaviours', 'identifier' => 'B1', 'description' => 'Works independently and takes responsibility.'],
            ['course_id' => $dev->id, 'type' => 'behaviours', 'identifier' => 'B2', 'description' => 'Applies logical thinking.'],
            ['course_id' => $dev->id, 'type' => 'behaviours', 'identifier' => 'B3', 'description' => 'Maintains a productive, professional and secure working environment.'],
            ['course_id' => $dev->id, 'type' => 'behaviours', 'identifier' => 'B4', 'description' => 'Works collaboratively with a wide range of people in different roles, internally and externally.'],
            ['course_id' => $dev->id, 'type' => 'behaviours', 'identifier' => 'B5', 'description' => 'Acts with integrity with respect to ethical, legal and regulatory ensuring the protection of personal data, safety and security.'],
            ['course_id' => $dev->id, 'type' => 'behaviours', 'identifier' => 'B6', 'description' => 'Shows initiative and takes responsibility for solving problems within their own remit.'],
            ['course_id' => $dev->id, 'type' => 'behaviours', 'identifier' => 'B7', 'description' => 'Communicates effectively in a variety of situations to both a technical and non-technical audience.'],
            ['course_id' => $dev->id, 'type' => 'behaviours', 'identifier' => 'B8', 'description' => 'Shows curiosity to the business context in which the solution will be used.'],
            ['course_id' => $dev->id, 'type' => 'behaviours', 'identifier' => 'B9', 'description' => 'Committed to continued professional development.'],

                ['course_id' => $testing->id, 'type' => 'knowledge', 'identifier' => 'K1', 'description' => 'The relationship between testing and quality assurance and how testing contributes to higher quality.'],
                ['course_id' => $testing->id, 'type' => 'knowledge', 'identifier' => 'K2', 'description' => 'The difference between error, defect, and failure, including the distinction between the root cause of a defect and its effects.'],
                ['course_id' => $testing->id, 'type' => 'knowledge', 'identifier' => 'K3', 'description' => 'The impact of context on the test process, including the activities, tasks, and work products that support the test process.'],
                ['course_id' => $testing->id, 'type' => 'knowledge', 'identifier' => 'K4', 'description' => 'The need for traceability between the requirements/test basis and the test work products.'],
                ['course_id' => $testing->id, 'type' => 'knowledge', 'identifier' => 'K5', 'description' => 'The principles underpinning the psychology of testing, including how the required mindset differs from the development mindset and how this can influence the success of software testing activities.'],
                ['course_id' => $testing->id, 'type' => 'knowledge', 'identifier' => 'K6', 'description' => 'The importance of accuracy and clear documentation of software tests and defects.'],
                ['course_id' => $testing->id, 'type' => 'knowledge', 'identifier' => 'K7', 'description' => 'The relationship between test activities and software development activities in the Software Development Lifecycle.'],
                ['course_id' => $testing->id, 'type' => 'knowledge', 'identifier' => 'K8', 'description' => 'The application of testing across different recognized software development methodologies (sequential and iterative).'],
                ['course_id' => $testing->id, 'type' => 'knowledge', 'identifier' => 'K9', 'description' => 'The range and features of software test types within the broad categories of Functional, Non-Functional, White Box/Structural, and Change-related Testing.'],
                ['course_id' => $testing->id, 'type' => 'knowledge', 'identifier' => 'K10', 'description' => 'The objectives and approaches for testing at different Test Levels (such as Unit Testing, Component Integration Testing, System Testing, System Integration Testing, and User Acceptance Testing).'],
                ['course_id' => $testing->id, 'type' => 'knowledge', 'identifier' => 'K11', 'description' => 'The role of static testing techniques and the review process in early defect detection.'],
                ['course_id' => $testing->id, 'type' => 'knowledge', 'identifier' => 'K12', 'description' => 'The characteristics of Black Box, White Box, and Experience-based Test Techniques.'],
                ['course_id' => $testing->id, 'type' => 'knowledge', 'identifier' => 'K13', 'description' => 'The application of common Black Box Techniques to derive test conditions and test cases (Equivalence Partitioning, Boundary Value Analysis, Decision Table Testing, and State Transition Testing).'],
                ['course_id' => $testing->id, 'type' => 'knowledge', 'identifier' => 'K14', 'description' => 'The role of software testing within the context of project and product risk reduction in the systems development life cycle.'],
                ['course_id' => $testing->id, 'type' => 'knowledge', 'identifier' => 'K15', 'description' => 'The defect management process.'],
                ['course_id' => $testing->id, 'type' => 'knowledge', 'identifier' => 'K16', 'description' => 'The typical metrics used to support the monitoring and control of testing.'],
                ['course_id' => $testing->id, 'type' => 'knowledge', 'identifier' => 'K17', 'description' => 'The classification of tools to support testing.'],
                ['course_id' => $testing->id, 'type' => 'knowledge', 'identifier' => 'K18', 'description' => 'The role of test automation in the context of the software development lifecycle.'],
                ['course_id' => $testing->id, 'type' => 'knowledge', 'identifier' => 'K19', 'description' => 'The need for conformance to specific industry standards where appropriate (such as GDPR, health informatics, safety-critical, etc.) related to software testing.'],
                ['course_id' => $testing->id, 'type' => 'knowledge', 'identifier' => 'K20', 'description' => 'Where Software Testers fit within the wider team and the roles and responsibilities that others play.'],
                ['course_id' => $testing->id, 'type' => 'knowledge', 'identifier' => 'K21', 'description' => 'The characteristics of software architecture that impact software testing in the development lifecycle.'],
                ['course_id' => $testing->id, 'type' => 'knowledge', 'identifier' => 'K22', 'description' => 'The core testing behaviors, skills, and tools that are common to developers, testers, and multi-skilled roles in development lifecycles.'],
                ['course_id' => $testing->id, 'type' => 'knowledge', 'identifier' => 'K23', 'description' => 'The typical security vulnerabilities that should be addressed by testing in general and specifically by penetration testing.'],
            
                // Skills
                ['course_id' => $testing->id, 'type' => 'skills', 'identifier' => 'S1', 'description' => 'Apply static test techniques.'],
                ['course_id' => $testing->id, 'type' => 'skills', 'identifier' => 'S2', 'description' => 'Apply Black Box test techniques such as Equivalence Partitioning, Boundary Value Analysis, Decision Table Testing, and State Transition Testing.'],
                ['course_id' => $testing->id, 'type' => 'skills', 'identifier' => 'S3', 'description' => 'Analyze test objectives and requirements/test basis to define test scope and coverage criteria.'],
                ['course_id' => $testing->id, 'type' => 'skills', 'identifier' => 'S4', 'description' => 'Use tools to automate, manage, or support any test activity.'],
                ['course_id' => $testing->id, 'type' => 'skills', 'identifier' => 'S5', 'description' => 'Apply a regression strategy, including selection of tests, maintenance of regression suites, and identifying tests suitable for automation.'],
                ['course_id' => $testing->id, 'type' => 'skills', 'identifier' => 'S6', 'description' => 'Use defect tracking tools.'],
                ['course_id' => $testing->id, 'type' => 'skills', 'identifier' => 'S7', 'description' => 'Adapt and apply testing activities according to industry-standard development methodologies (sequential and iterative).'],
                ['course_id' => $testing->id, 'type' => 'skills', 'identifier' => 'S8', 'description' => 'Apply the range of different software test types within the broad categories of Functional, Non-Functional (Security, Performance & Usability), and White Box/Structural Testing.'],
                ['course_id' => $testing->id, 'type' => 'skills', 'identifier' => 'S9', 'description' => 'Apply and support testing at different Test Levels appropriate to the Software Development Lifecycle (such as Unit Testing, Component Integration Testing, System Testing, System Integration Testing, and User Acceptance Testing), taking into account the fundamentals of testing.'],
                ['course_id' => $testing->id, 'type' => 'skills', 'identifier' => 'S10', 'description' => 'Conform to specific industry standards where appropriate (such as GDPR, health informatics, safety-critical, etc.) related to software testing.'],
                ['course_id' => $testing->id, 'type' => 'skills', 'identifier' => 'S11', 'description' => 'Maintain up-to-date knowledge of technological developments in the field of Software Testing.'],
                ['course_id' => $testing->id, 'type' => 'skills', 'identifier' => 'S12', 'description' => 'Record and interpret test progress and results, communicating test status to the relevant stakeholders.'],
                ['course_id' => $testing->id, 'type' => 'skills', 'identifier' => 'S13', 'description' => 'Design and follow tests to achieve coverage criteria.'],
            
                // Behaviours
                ['course_id' => $testing->id, 'type' => 'behaviours', 'identifier' => 'B1', 'description' => 'Maintains a productive, professional, and secure working environment.'],
                ['course_id' => $testing->id, 'type' => 'behaviours', 'identifier' => 'B2', 'description' => 'Works independently and takes responsibility.'],
                ['course_id' => $testing->id, 'type' => 'behaviours', 'identifier' => 'B3', 'description' => 'A problem-solving mindset within their own remit, being inquisitive and resourceful when faced with a problem to solve.'],
                ['course_id' => $testing->id, 'type' => 'behaviours', 'identifier' => 'B4', 'description' => 'Uses a range of logical and analytical reasoning approaches to create practical solutions.'],
                ['course_id' => $testing->id, 'type' => 'behaviours', 'identifier' => 'B5', 'description' => 'A tenacious approach to problem solving by working to identify and resolve issues.'],
                ['course_id' => $testing->id, 'type' => 'behaviours', 'identifier' => 'B6', 'description' => 'Resilient and positive mental attitude when dealing with difficult situations.'],
                ['course_id' => $testing->id, 'type' => 'behaviours', 'identifier' => 'B7', 'description' => 'Committed to continuous learning and professional development.'],

                ['course_id' => $apm_l4->id, 'type' => 'knowledge', 'identifier' => 'K1', 'description' => 'The differences between projects and business as usual.'],
    ['course_id' => $apm_l4->id, 'type' => 'knowledge', 'identifier' => 'K2', 'description' => 'The importance of alignment between the project and organisational objectives.'],
    ['course_id' => $apm_l4->id, 'type' => 'knowledge', 'identifier' => 'K3', 'description' => 'The interdependencies between project, programme, and portfolio management.'],
    ['course_id' => $apm_l4->id, 'type' => 'knowledge', 'identifier' => 'K4', 'description' => 'Techniques used to understand the project context, such as PESTLE, SWOT, or VUCA.'],
    ['course_id' => $apm_l4->id, 'type' => 'knowledge', 'identifier' => 'K5', 'description' => 'The need and benefit of the project governance structure, requirements, and process and the impact on their role.'],
    ['course_id' => $apm_l4->id, 'type' => 'knowledge', 'identifier' => 'K6', 'description' => 'The differences and comparative benefits between functional, matrix, and project structures.'],
    ['course_id' => $apm_l4->id, 'type' => 'knowledge', 'identifier' => 'K7', 'description' => 'Different roles and responsibilities within a project environment.'],
    ['course_id' => $apm_l4->id, 'type' => 'knowledge', 'identifier' => 'K8', 'description' => 'The differences and comparative benefits between linear, iterative, and hybrid life cycle approaches.'],
    ['course_id' => $apm_l4->id, 'type' => 'knowledge', 'identifier' => 'K9', 'description' => 'Importance, content, and purpose of a business case.'],
    ['course_id' => $apm_l4->id, 'type' => 'knowledge', 'identifier' => 'K10', 'description' => 'Approaches to the maintenance of a business case and the management of the benefits achieved upon the successful delivery of the project.'],
    ['course_id' => $apm_l4->id, 'type' => 'knowledge', 'identifier' => 'K11', 'description' => 'The purpose, format, and significance of the project management plan.'],
    ['course_id' => $apm_l4->id, 'type' => 'knowledge', 'identifier' => 'K12', 'description' => 'Methods used to define, record, integrate, deliver, and manage scope.'],
    ['course_id' => $apm_l4->id, 'type' => 'knowledge', 'identifier' => 'K13', 'description' => 'The identification, analysis, and management of stakeholders.'],
    ['course_id' => $apm_l4->id, 'type' => 'knowledge', 'identifier' => 'K14', 'description' => 'Communication techniques and approaches to interact with stakeholders to meet their requirements.'],
    ['course_id' => $apm_l4->id, 'type' => 'knowledge', 'identifier' => 'K15', 'description' => 'The use of information management.'],
    ['course_id' => $apm_l4->id, 'type' => 'knowledge', 'identifier' => 'K16', 'description' => 'Techniques for managing conflict and negotiation.'],
    ['course_id' => $apm_l4->id, 'type' => 'knowledge', 'identifier' => 'K17', 'description' => 'Techniques for working collaboratively within a team and with stakeholders.'],
    ['course_id' => $apm_l4->id, 'type' => 'knowledge', 'identifier' => 'K18', 'description' => 'How and when to apply different estimating methods.'],
    ['course_id' => $apm_l4->id, 'type' => 'knowledge', 'identifier' => 'K19', 'description' => 'Configuration management and change control.'],
    ['course_id' => $apm_l4->id, 'type' => 'knowledge', 'identifier' => 'K20', 'description' => 'The principles of earned value management (EVM) and the interpretation of EVM information.'],
    ['course_id' => $apm_l4->id, 'type' => 'knowledge', 'identifier' => 'K21', 'description' => 'Project scheduling and maintenance, including critical path analysis.'],
    ['course_id' => $apm_l4->id, 'type' => 'knowledge', 'identifier' => 'K22', 'description' => 'Allocation and management of resources throughout the project life cycle.'],
    ['course_id' => $apm_l4->id, 'type' => 'knowledge', 'identifier' => 'K23', 'description' => 'Principles of project risk and issue management.'],
    ['course_id' => $apm_l4->id, 'type' => 'knowledge', 'identifier' => 'K24', 'description' => 'Procurement strategies and processes that are both ethical and sustainable.'],
    ['course_id' => $apm_l4->id, 'type' => 'knowledge', 'identifier' => 'K25', 'description' => 'The role and purpose of quality requirements, planning and control in a project environment.'],
    ['course_id' => $apm_l4->id, 'type' => 'knowledge', 'identifier' => 'K26', 'description' => 'Principles for evaluating project success, including how lessons learned are captured and can impact future project delivery.'],
    ['course_id' => $apm_l4->id, 'type' => 'knowledge', 'identifier' => 'K27', 'description' => 'Relevant regulations and legislation such as data protection, and how they impact on their role.'],
    ['course_id' => $apm_l4->id, 'type' => 'knowledge', 'identifier' => 'K28', 'description' => 'The impact of project objectives and how to respond to challenges around sustainability and the UK Government’s policy to achieve net carbon zero.'],
    ['course_id' => $apm_l4->id, 'type' => 'knowledge', 'identifier' => 'K29', 'description' => 'Principles of conducting project management activities which are ethical and inclusive.'],
    ['course_id' => $apm_l4->id, 'type' => 'knowledge', 'identifier' => 'K30', 'description' => 'Technology and software used in the performance of project management activities.'],
    ['course_id' => $apm_l4->id, 'type' => 'knowledge', 'identifier' => 'K31', 'description' => 'Presentation tools and techniques.'],

    ['course_id' => $apm_l4->id, 'type' => 'behaviours', 'identifier' => 'B1', 'description' => 'Works flexibly and adapts to circumstances.'],
    ['course_id' => $apm_l4->id, 'type' => 'behaviours', 'identifier' => 'B2', 'description' => 'Works collaboratively and builds strong relationships with others across the organisation and external stakeholders.'],
    ['course_id' => $apm_l4->id, 'type' => 'behaviours', 'identifier' => 'B3', 'description' => 'Has accountability and ownership of their tasks and workload.'],
    ['course_id' => $apm_l4->id, 'type' => 'behaviours', 'identifier' => 'B4', 'description' => 'Operates professionally with integrity and confidentiality.'],
    ['course_id' => $apm_l4->id, 'type' => 'behaviours', 'identifier' => 'B5', 'description' => 'Seeks learning opportunities and continuous professional development.'],

    ['course_id' => $apm_l4->id, 'type' => 'skills', 'identifier' => 'S1', 'description' => 'Use project monitoring and reporting techniques to track, interpret and report on performance.'],
    ['course_id' => $apm_l4->id, 'type' => 'skills', 'identifier' => 'S2', 'description' => 'Manage and engage with stakeholders.'],
    ['course_id' => $apm_l4->id, 'type' => 'skills', 'identifier' => 'S3', 'description' => 'Influence and negotiate with others to create a positive outcome for the project.'],
    ['course_id' => $apm_l4->id, 'type' => 'skills', 'identifier' => 'S4', 'description' => 'Resolve conflict as and when required with stakeholders within limits of responsibility.'],
    ['course_id' => $apm_l4->id, 'type' => 'skills', 'identifier' => 'S5', 'description' => 'Adapt communications to different stakeholders.'],
    ['course_id' => $apm_l4->id, 'type' => 'skills', 'identifier' => 'S6', 'description' => 'Communicate and support the project vision, to ensure buy-in to the project objectives.'],
    ['course_id' => $apm_l4->id, 'type' => 'skills', 'identifier' => 'S7', 'description' => 'Collate and analyse information and provide input to support negotiations relating to project objectives.'],
    ['course_id' => $apm_l4->id, 'type' => 'skills', 'identifier' => 'S8', 'description' => 'Monitor and analyse project budgets.'],
    ['course_id' => $apm_l4->id, 'type' => 'skills', 'identifier' => 'S9', 'description' => 'Review and provide feedback on a project business case to ensure the project remains valid.'],
    ['course_id' => $apm_l4->id, 'type' => 'skills', 'identifier' => 'S10', 'description' => 'Apply change control processes to support the management of project scope.'],
    ['course_id' => $apm_l4->id, 'type' => 'skills', 'identifier' => 'S11', 'description' => 'Evaluate an integrated project management plan to provide recommendations on areas for improvement.'],
    ['course_id' => $apm_l4->id, 'type' => 'skills', 'identifier' => 'S12', 'description' => 'Prepare, monitor, and schedule activities that contribute to the delivery of the overall project schedule and objectives.'],
    ['course_id' => $apm_l4->id, 'type' => 'skills', 'identifier' => 'S13', 'description' => 'Evaluate and make recommendations on the risk management plan to threats to delivery and recommend solutions.'],
    ['course_id' => $apm_l4->id, 'type' => 'skills', 'identifier' => 'S14', 'description' => 'Identify and monitor project risks and issues; and plan and implement responses to them.'],
    ['course_id' => $apm_l4->id, 'type' => 'skills', 'identifier' => 'S15', 'description' => 'Deliver a Quality Management Plan which contributes to quality control processes.'],
    ['course_id' => $apm_l4->id, 'type' => 'skills', 'identifier' => 'S16', 'description' => 'Use an organisation’s continual improvement process including lessons learned to improve performance.'],
    ['course_id' => $apm_l4->id, 'type' => 'skills', 'identifier' => 'S17', 'description' => 'Support the preparation or maintenance of a resource management plan for project activities.'],
    ['course_id' => $apm_l4->id, 'type' => 'skills', 'identifier' => 'S18', 'description' => 'Work with stakeholders to deliver the project.'],
    ['course_id' => $apm_l4->id, 'type' => 'skills', 'identifier' => 'S19', 'description' => 'Use digital tools and software to meet project objectives for example research, collaboration, presentations, and resolution of problems.'],
    ['course_id' => $apm_l4->id, 'type' => 'skills', 'identifier' => 'S20', 'description' => 'Provide underpinning data to support the written submission through the governance process.'],
    ['course_id' => $apm_l4->id, 'type' => 'skills', 'identifier' => 'S21', 'description' => 'Work within the approved project budget.'],
    ['course_id' => $apm_l4->id, 'type' => 'skills', 'identifier' => 'S22', 'description' => 'Ensure that integrated schedules support critical path analysis, interface management, resource forecasting and risk management.'],
    ['course_id' => $apm_l4->id, 'type' => 'skills', 'identifier' => 'S23', 'description' => 'Apply relevant legislation, regulations, codes of practice, and ethical guidance where appropriate to their work.'],
    ['course_id' => $apm_l4->id, 'type' => 'skills', 'identifier' => 'S24', 'description' => 'Use data to inform decisions on actions to take to mitigate risks on project.'],
    ['course_id' => $apm_l4->id, 'type' => 'skills', 'identifier' => 'S25', 'description' => 'Use configuration management and change control to schedule and maintain projects.'],
    ['course_id' => $apm_l4->id, 'type' => 'skills', 'identifier' => 'S26', 'description' => 'Manages resources through the project lifecycle.'],
        ['course_id' => $acc->id, 'type' => 'knowledge', 'identifier' => 'K1', 'description' => 'The characteristics and categories of disabilities (including temporary, situational and permanent disabilities) and how these affect individuals.'],
        ['course_id' => $acc->id, 'type' => 'knowledge', 'identifier' => 'K2', 'description' => 'Commonly used accessibility guidelines (for example the Web Content Accessibility Guidelines, EN301549 and Section508), methods to implement and achieve conformance and how these assist users with disabilities.'],
        ['course_id' => $acc->id, 'type' => 'knowledge', 'identifier' => 'K3', 'description' => 'How accessibility is managed and integrated within an enterprise environment including policies, and reasonable adjustments.'],
        ['course_id' => $acc->id, 'type' => 'knowledge', 'identifier' => 'K4', 'description' => 'How to utilise productivity suites ensuring output is accessible and advising on the implementation of accessibility features and content.'],
        ['course_id' => $acc->id, 'type' => 'knowledge', 'identifier' => 'K5', 'description' => 'The implications and effect on users with disabilities, and UK businesses of international disability legislation (including Equality Act 2010, Public Sector Bodies (Websites and Mobile Applications) No. 2 Accessibility Regulations 2018 and Accessible Canada Act C81 2018).'],
        ['course_id' => $acc->id, 'type' => 'knowledge', 'identifier' => 'K6', 'description' => 'How to present using relevant technologies and aids in a manner that communicates the information (including a business case) to the chosen target audience, and understand the key facts and figures relating to accessibility.'],
        ['course_id' => $acc->id, 'type' => 'knowledge', 'identifier' => 'K7', 'description' => 'The process to set-up, moderate and conduct activities relating to hosting workshops including moderation usability testing, user research testing and end-user testing.'],
        ['course_id' => $acc->id, 'type' => 'knowledge', 'identifier' => 'K8', 'description' => 'The basics of Hyper Text Mark-up Language, Cascading Style Sheets, JavaScript and Accessibility Rich Internet Applications, and how these should be used to enhance the accessibility of services (for example alt text, dynamic content, colour contrast).'],
        ['course_id' => $acc->id, 'type' => 'knowledge', 'identifier' => 'K9', 'description' => 'How mobile applications are developed using appropriate development applications and the basics of the languages used.'],
        ['course_id' => $acc->id, 'type' => 'knowledge', 'identifier' => 'K10', 'description' => 'The fundamentals of the Web Content Accessibility Guidelines (WCAG), including the purpose, application and utilisation of WCAG in a variety of situations (for example web, mobile, desktop applications).'],
        ['course_id' => $acc->id, 'type' => 'knowledge', 'identifier' => 'K11', 'description' => 'The basic principles of project management (including project life cycle methodologies), and how accessibility considerations are integrated.'],
        ['course_id' => $acc->id, 'type' => 'knowledge', 'identifier' => 'K12', 'description' => 'The accessibility considerations when designing and developing an application\'s user experience using related standards and guidelines including ISO9241 Ergonomics of human-system interaction, The Principles of Universal Design by the Centre for Universal Design and the Web Content Accessibility Guidelines to create an inclusive design.'],
        ['course_id' => $acc->id, 'type' => 'knowledge', 'identifier' => 'K13', 'description' => 'How to use assistive technologies (both digital and physical), their use-cases and functionality, degrees of complexity (hi-tech, low-tech and no-tech).'],
        ['course_id' => $acc->id, 'type' => 'knowledge', 'identifier' => 'K14', 'description' => 'How assistive technologies interact with other digital technologies.'],
        ['course_id' => $acc->id, 'type' => 'knowledge', 'identifier' => 'K15', 'description' => 'The principles and application of testing methodologies to accessibility criteria and assistive technologies, and the impact of accessibility findings (including test documentation).'],
        ['course_id' => $acc->id, 'type' => 'knowledge', 'identifier' => 'K16', 'description' => 'How to construct a business report (for example document layout and contents).'],
        ['course_id' => $acc->id, 'type' => 'knowledge', 'identifier' => 'K17', 'description' => 'The purpose and importance of reasonable adjustments, and how these are managed.'],
        ['course_id' => $acc->id, 'type' => 'knowledge', 'identifier' => 'K18', 'description' => 'Best practices regarding digital security including General Data Protection Regulations 2018, how these are applied to an organisation and the factors which can result in these being effective and how these can be mitigated.'],
        ['course_id' => $acc->id, 'type' => 'knowledge', 'identifier' => 'K19', 'description' => 'The security considerations relating to the installation and utilisation of assistive technologies, how these tools may be misidentified by common security practices and the methods to mitigate such security constraints.'],
        ['course_id' => $acc->id, 'type' => 'knowledge', 'identifier' => 'K20', 'description' => 'How to communicate through different mediums, including tailoring communications to different user groups.'],
        ['course_id' => $acc->id, 'type' => 'knowledge', 'identifier' => 'K21', 'description' => 'How to use incident management tools, triage incidents and appropriately communicate with assistive technology users.'],
        ['course_id' => $acc->id, 'type' => 'knowledge', 'identifier' => 'K22', 'description' => 'How to audit digital applications (including web and mobile applications) against digital assistive technologies including screen readers, screen magnifiers, speech to text and literacy aids.'],
        ['course_id' => $acc->id, 'type' => 'knowledge', 'identifier' => 'K23', 'description' => 'The preparation and processes required to conduct training with a variety of user groups for example project managers, web designers, developers, end users and line management.'],
        ['course_id' => $acc->id, 'type' => 'knowledge', 'identifier' => 'K24', 'description' => 'How accessibility fits into the wider digital landscape, including current/future applicable regulatory requirements, and case law in the area of discriminating against employees with a disability.'],
        ['course_id' => $acc->id, 'type' => 'knowledge', 'identifier' => 'K25', 'description' => 'How to use data ethically and the implications for wider society, with respect to the use of data, automation and artificial intelligence.'],
        ['course_id' => $acc->id, 'type' => 'skills', 'identifier' => 'S1', 'description' => 'Present information, (for example business cases, testing findings, general information etc.) to a variety of audiences to ensure understanding.'],
        ['course_id' => $acc->id, 'type' => 'skills', 'identifier' => 'S2', 'description' => 'Use hardware and software based assistive technologies for a variety of applications (for example testing, training etc.).'],
        ['course_id' => $acc->id, 'type' => 'skills', 'identifier' => 'S3', 'description' => 'Use Interpersonal skills to develop and maintain effective and credible professional relationships both within and outside the team.'],
        ['course_id' => $acc->id, 'type' => 'skills', 'identifier' => 'S4', 'description' => 'Conduct testing against a variety of platforms using appropriate standards and/or guidelines and assistive technologies.'],
        ['course_id' => $acc->id, 'type' => 'skills', 'identifier' => 'S5', 'description' => 'Conduct workshops, surveys or focus groups, including the set-up, running and conclusion activities.'],
        ['course_id' => $acc->id, 'type' => 'skills', 'identifier' => 'S6', 'description' => 'Both written and verbal communication skills when working as a team or individually.'],
        ['course_id' => $acc->id, 'type' => 'skills', 'identifier' => 'S7', 'description' => 'Solve problems using a logical and analytical approach.'],
        ['course_id' => $acc->id, 'type' => 'skills', 'identifier' => 'S8', 'description' => 'Plan, manage and deliver accessibility activities, in particular workshops, training and technical activities.'],
        ['course_id' => $acc->id, 'type' => 'skills', 'identifier' => 'S9', 'description' => 'Work collaboratively within a team environment, sharing and receiving information to ensure efficient and effective use of time.'],
        ['course_id' => $acc->id, 'type' => 'skills', 'identifier' => 'S10', 'description' => 'Support colleagues with accessibility-related queries.'],
        ['course_id' => $acc->id, 'type' => 'skills', 'identifier' => 'S11', 'description' => 'Create and manage a report against digital accessibility, highlighting both findings and risks associated with particular groups of users (for example, impairments).'],
        ['course_id' => $acc->id, 'type' => 'skills', 'identifier' => 'S12', 'description' => 'Plan, manage and deliver digital accessibility, inclusive of assistive technologies, guidelines, testing and strategies to mitigate findings.'],
        ['course_id' => $acc->id, 'type' => 'skills', 'identifier' => 'S13', 'description' => 'Keep up to date with digital accessibility issues, regulations, and strategies in the wider technology sector.'],
        ['course_id' => $acc->id, 'type' => 'skills', 'identifier' => 'S14', 'description' => 'Support individuals with disabilities to understand and use assistive technologies to suit their needs.'],
        ['course_id' => $cyber_security_l4->id, 'type' => 'knowledge', 'identifier' => 'K1', 'description' => 'Principles of networks: OSI and TCP/IP models, data, protocols and how they relate to each other; the main routing protocols; the main factors affecting network performance including typical failure modes in protocols and approaches to error control; virtual networking.'],
  ['course_id' => $cyber_security_l4->id, 'type' => 'knowledge', 'identifier' => 'K2', 'description' => 'The concepts, main functions and features of at least three Operating Systems (OS) and their security functions and associated security features.'],
  ['course_id' => $cyber_security_l4->id, 'type' => 'knowledge', 'identifier' => 'K3', 'description' => 'Cyber security concepts and why cyber security matters to business and society; Security assurance concepts and how assurance may be achieved in practice including penetration testing and extrinsic assurance methods.'],
  ['course_id' => $cyber_security_l4->id, 'type' => 'knowledge', 'identifier' => 'K4', 'description' => 'The main types of common attack techniques; also the role of human behaviour, including the significance of the "insider threat". Techniques and strategies to defend against attack techniques and mitigate hazards.'],
  ['course_id' => $cyber_security_l4->id, 'type' => 'knowledge', 'identifier' => 'K5', 'description' => 'The significance of identified trends in cyber security threats and understand the value and risk of this analysis. How to deal with emerging attack techniques (including "zero day"), hazards and vulnerabilities relevant to the digital systems and business environment.'],
  ['course_id' => $cyber_security_l4->id, 'type' => 'knowledge', 'identifier' => 'K6', 'description' => 'Lifecycle and service management practices to an established standard, such as Information Technology Infrastructure Library (ITIL) foundation level.'],
  ['course_id' => $cyber_security_l4->id, 'type' => 'knowledge', 'identifier' => 'K7', 'description' => 'Cyber incident response processes, incident management processes and evidence collection/preservation requirements to support incident investigation.'],
  ['course_id' => $cyber_security_l4->id, 'type' => 'knowledge', 'identifier' => 'K8', 'description' => 'Understand the main features, applicability and how to apply the significant law, regulations and standards relevant specifically to cyber security.'],
  ['course_id' => $cyber_security_l4->id, 'type' => 'knowledge', 'identifier' => 'K9', 'description' => 'Ethical principles and codes of good practice of at least one significant cyber security professional body and the ethical responsibilities of a cyber security professional.'],
  ['course_id' => $cyber_security_l4->id, 'type' => 'knowledge', 'identifier' => 'K10', 'description' => 'How to analyse employer or customer requirements to derive security objectives and, taking account of threats and overall context, develop a security case with reasoned justification.'],
  ['course_id' => $cyber_security_l4->id, 'type' => 'knowledge', 'identifier' => 'K11', 'description' => 'Horizon scanning including use of recognised sources of threat intelligence and vulnerabilities.'],
  ['course_id' => $cyber_security_l4->id, 'type' => 'knowledge', 'identifier' => 'K12', 'description' => 'Common security architectures and methodologies. Awareness of reputable security architectures that incorporate hardware and software components, and sources of architecture patterns and guidance.'],
  ['course_id' => $cyber_security_l4->id, 'type' => 'knowledge', 'identifier' => 'K13', 'description' => 'The basic terminology and concepts of cryptography; common cryptography techniques in use; the importance of effective key management and the main techniques used.'],
  ['course_id' => $cyber_security_l4->id, 'type' => 'knowledge', 'identifier' => 'K14', 'description' => 'Risk assessment and audit methodologies and approaches to risk treatment; the role of the risk owner in contrast with other stakeholders.'],
  ['course_id' => $cyber_security_l4->id, 'type' => 'knowledge', 'identifier' => 'K15', 'description' => 'Principles of security management systems, including governance, organisational structure, roles, policies, standards, guidelines and how these all work together to deliver the identified security outcomes.'],
  ['course_id' => $cyber_security_l4->id, 'type' => 'knowledge', 'identifier' => 'K16', 'description' => 'Function and features of significant digital system components; typical architectures; common vulnerabilities in digital systems; principles and common practice in digital system security.'],
  ['course_id' => $cyber_security_l4->id, 'type' => 'knowledge', 'identifier' => 'K17', 'description' => 'Programming or scripting languages.'],
  ['course_id' => $cyber_security_l4->id, 'type' => 'skills', 'identifier' => 'S1', 'description' => 'Discover vulnerabilities in a system by using a mix of research and practical exploration.'],
  ['course_id' => $cyber_security_l4->id, 'type' => 'skills', 'identifier' => 'S2', 'description' => 'Analyse and evaluate security threats and hazards to a system or service or processes.'],
  ['course_id' => $cyber_security_l4->id, 'type' => 'skills', 'identifier' => 'S3', 'description' => 'Research and investigate common attack techniques and relate these to observed system behaviour and recommend how to defend against them.'],
  ['course_id' => $cyber_security_l4->id, 'type' => 'skills', 'identifier' => 'S4', 'description' => 'Undertake security risk assessments for simple systems without direct supervision and propose basic remediation advice.'],
  ['course_id' => $cyber_security_l4->id, 'type' => 'skills', 'identifier' => 'S5', 'description' => 'Source and analyse security cases, describe mitigated threats and identify any residual areas of concern.'],
  ['course_id' => $cyber_security_l4->id, 'type' => 'skills', 'identifier' => 'S6', 'description' => 'Analyse employer or customer requirements to derive security objectives and develop a security case with reasoned justification.'],
  ['course_id' => $cyber_security_l4->id, 'type' => 'skills', 'identifier' => 'S7', 'description' => 'Identify and follow organisational policies and standards for information and cyber security.'],
  ['course_id' => $cyber_security_l4->id, 'type' => 'skills', 'identifier' => 'S8', 'description' => 'Configure, deploy and use computer, digital network and cyber security technology.'],
  ['course_id' => $cyber_security_l4->id, 'type' => 'skills', 'identifier' => 'S9', 'description' => 'Recommend improvements to cyber security posture based on research into potential threats and considering threat trends.'],
  ['course_id' => $cyber_security_l4->id, 'type' => 'skills', 'identifier' => 'S10', 'description' => 'Design, build, test and troubleshoot a network with multiple subnets to a given design requirement.'],
  ['course_id' => $cyber_security_l4->id, 'type' => 'skills', 'identifier' => 'S11', 'description' => 'Analyse security requirements for a system and propose resolution of conflicting requirements.'],
  ['course_id' => $cyber_security_l4->id, 'type' => 'skills', 'identifier' => 'S12', 'description' => 'Design and build systems in accordance with a security case within defined parameters.'],
  ['course_id' => $cyber_security_l4->id, 'type' => 'skills', 'identifier' => 'S13', 'description' => 'Write program code or scripts to meet a design requirement in accordance with coding standards.'],
  ['course_id' => $cyber_security_l4->id, 'type' => 'skills', 'identifier' => 'S14', 'description' => 'Design systems employing encryption to meet defined security objectives and manage encryption keys.'],
  ['course_id' => $cyber_security_l4->id, 'type' => 'skills', 'identifier' => 'S15', 'description' => 'Use tools and techniques to prevent breaches to digital system security.'],

  ['course_id' => $cyber_security_l4->id, 'type' => 'behaviours', 'identifier' => 'B1', 'description' => 'Applies logical thinking, for example, uses clear and valid reasoning when making decisions related to work instructions.'],
  ['course_id' => $cyber_security_l4->id, 'type' => 'behaviours', 'identifier' => 'B2', 'description' => 'Works effectively with data to see patterns, trends and draw meaningful conclusions.'],
  ['course_id' => $cyber_security_l4->id, 'type' => 'behaviours', 'identifier' => 'B3', 'description' => 'Demonstrates attention to detail, for example, ensures that all records are accurate and completed to the highest standard.'],
  ['course_id' => $cyber_security_l4->id, 'type' => 'behaviours', 'identifier' => 'B4', 'description' => 'Demonstrates a willingness to support others, e.g., offers assistance to other colleagues as required.'],
  ['course_id' => $cyber_security_l4->id, 'type' => 'behaviours', 'identifier' => 'B5', 'description' => 'Contributes to decision-making by supporting colleagues in applying appropriate guidelines and standards in all situations.'],
  ['course_id' => $cyber_security_l4->id, 'type' => 'behaviours', 'identifier' => 'B6', 'description' => 'Confidently identifies risks and opportunities and suggests practical approaches to resolve issues.'],
  ['course_id' => $cyber_security_l4->id, 'type' => 'behaviours', 'identifier' => 'B7', 'description' => 'Demonstrates an understanding of professional ethical principles and applies them when making decisions.'],
  ['course_id' => $cyber_security_l4->id, 'type' => 'behaviours', 'identifier' => 'B8', 'description' => 'Communicates clearly, e.g., conveys ideas to a range of stakeholders in a straightforward and practical way.'],
      
    ];

        foreach ($ksbs as $ksb) {
            Ksb::create($ksb);
        }
    }
}
